
// This file has been generated by the GUI designer. Do not modify.
namespace PutkEd
{
	public partial class PointerEditor
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Entry m_tbox;
		
		private global::Gtk.Button button132;
		
		private global::Gtk.Button button133;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PutkEd.PointerEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PutkEd.PointerEditor";
			// Container child PutkEd.PointerEditor.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.m_tbox = new global::Gtk.Entry ();
			this.m_tbox.Sensitive = false;
			this.m_tbox.Name = "m_tbox";
			this.m_tbox.IsEditable = false;
			this.m_tbox.InvisibleChar = '●';
			this.hbox1.Add (this.m_tbox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.m_tbox]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button132 = new global::Gtk.Button ();
			this.button132.CanFocus = true;
			this.button132.Name = "button132";
			this.button132.UseUnderline = true;
			this.button132.Label = global::Mono.Unix.Catalog.GetString ("*");
			this.hbox1.Add (this.button132);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button132]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button133 = new global::Gtk.Button ();
			this.button133.CanFocus = true;
			this.button133.Name = "button133";
			this.button133.UseUnderline = true;
			this.button133.Label = global::Mono.Unix.Catalog.GetString ("X");
			this.hbox1.Add (this.button133);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button133]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button132.Clicked += new global::System.EventHandler (this.OnStarClicked);
			this.button133.Clicked += new global::System.EventHandler (this.OnClearClicked);
		}
	}
}
