
// This file has been generated by the GUI designer. Do not modify.
namespace PutkEd
{
	public partial class AssetEditorWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button m_save;
		
		private global::Gtk.Label m_path;
		
		private global::Gtk.Frame m_frame;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PutkEd.AssetEditorWindow
			this.Name = "PutkEd.AssetEditorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("AssetEditorWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child PutkEd.AssetEditorWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.m_save = new global::Gtk.Button ();
			this.m_save.CanFocus = true;
			this.m_save.Name = "m_save";
			this.m_save.UseUnderline = true;
			this.m_save.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.hbox1.Add (this.m_save);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.m_save]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(10));
			// Container child hbox1.Gtk.Box+BoxChild
			this.m_path = new global::Gtk.Label ();
			this.m_path.Name = "m_path";
			this.m_path.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.m_path);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.m_path]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.m_frame = new global::Gtk.Frame ();
			this.m_frame.Name = "m_frame";
			this.m_frame.ShadowType = ((global::Gtk.ShadowType)(0));
			this.vbox2.Add (this.m_frame);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.m_frame]));
			w4.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.m_save.Clicked += new global::System.EventHandler (this.OnSaveClicked);
		}
	}
}
