
// This file has been generated by the GUI designer. Do not modify.
namespace PutkEd
{
	public partial class TextEditor
	{
		private global::Gtk.Entry m_text;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PutkEd.TextEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PutkEd.TextEditor";
			// Container child PutkEd.TextEditor.Gtk.Container+ContainerChild
			this.m_text = new global::Gtk.Entry ();
			this.m_text.CanFocus = true;
			this.m_text.Name = "m_text";
			this.m_text.IsEditable = true;
			this.m_text.InvisibleChar = '●';
			this.Add (this.m_text);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
