
// This file has been generated by the GUI designer. Do not modify.
namespace PutkEd
{
	public partial class TextFieldEditor
	{
		private global::Gtk.Button m_openEditor;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PutkEd.TextFieldEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PutkEd.TextFieldEditor";
			// Container child PutkEd.TextFieldEditor.Gtk.Container+ContainerChild
			this.m_openEditor = new global::Gtk.Button ();
			this.m_openEditor.CanFocus = true;
			this.m_openEditor.Name = "m_openEditor";
			this.m_openEditor.UseUnderline = true;
			this.m_openEditor.Label = global::Mono.Unix.Catalog.GetString ("Open text editor");
			this.Add (this.m_openEditor);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
