#ifndef __FIELDTYPES_H__
#define __FIELDTYPES_H__

namespace putki
{
	enum field_type
	{
		FIELDTYPE_INT32,
		FIELDTYPE_UINT32,
		FIELDTYPE_FLOAT,
		FIELDTYPE_BYTE,
		FIELDTYPE_BOOL,
		FIELDTYPE_STRING,
		FIELDTYPE_POINTER,
		FIELDTYPE_PATH,
		FIELDTYPE_STRUCT_INSTANCE,
		FIELDTYPE_ENUM,
		FIELDTYPE_FILE
	};
}

#endif