// Both the data dll and the putki builder assumes it can link with a function
// called app_bind_putki_types.

namespace inki
{
	// these are generated by the putki complier.
	void bind_claw();
}

// Bind all types used by the application, if more than one.
void app_bind_putki_types()
{
	inki::bind_claw();
}
