
// This file has been generated by the GUI designer. Do not modify.
namespace PutkEd
{
	public partial class ArrayEditor
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PutkEd.ArrayEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PutkEd.ArrayEditor";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
