
// This file has been generated by the GUI designer. Do not modify.
namespace ccguiputkedplugin
{
	public partial class WidgetEditWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ccguiputkedplugin.WidgetEditWindow
			this.Name = "ccguiputkedplugin.WidgetEditWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("WidgetEditWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
